local RadioStations = {
    NO = 0,
    BLAINE_COUNTRY_RADIO = "RADIO_11_TALK_02",
    MOTOMAMI_LOS_SANTOS = "RADIO_37_MOTOMAMI",
    MUSIC_LOCKER = "RADIO_35_DLC_HEI4_MLR",
    BLUE_ARK = "RADIO_12_REGGAE",
    WORLDWIDE_FM = "RADIO_13_JAZZ",
    FLYLO_FM = "RADIO_14_DANCE_02",
    THE_LOWDOWN = "RADIO_15_MOTOWN",
    THE_LAB = "RADIO_20_THELAB",
    RADIO_MIRROR_PARK = "RADIO_16_SILVERLAKE",
    KULT_FM = "RADIO_34_DLC_HEI4_KULT",
    SPACE = "RADIO_17_FUNK",
    VINEWOOD_BOULEVARD_RADIO = "RADIO_18_90S_ROCK",
    BLONDED_LOS_SANTOS = "RADIO_21_DLC_XM17",
    LOS_SANTOS_UNDERGROUND_RADIO = "RADIO_22_DLC_BATTLE_MIX1_RADIO",
    IFRUIT_RADIO = "RADIO_23_DLC_XM19_RADIO",
    SELF_RADIO = "RADIO_19_USER",
    STILL_SLIPPING_LOS_SANTOS = "RADIO_27_DLC_PRHEI4",
    LOS_SANTOS_ROCK_RADIO = "RADIO_01_CLASS_ROCK",
    NON_STOP_POP_FM = "RADIO_02_POP",
    RADIO_LOS_SANTOS = "RADIO_03_HIPHOP_NEW",
    CHANNEL_X = "RADIO_04_PUNK",
    REBEL_RADIO = "RADIO_06_COUNTRY",
    SOULWAX_FM = "RADIO_07_DANCE_01",
    EAST_LOS_FM = "RADIO_08_MEXICAN",
    WEST_COAST_CLASSIC = "RADIO_09_HIPHOP_OLD",
}

return {
    RadioStations = RadioStations
}
